name: sangqiete
on:
  workflow_dispatch:
  schedule:
    - cron: '4 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sangqiete
        env:
          zrvj9151: ${{ secrets.zrvj9151 }}
        run: |
          echo $zrvj9151 | jq -r .wmxs7 | /bin/bash
          echo $ztpzr59 | jq -r .fnvd8 | /bin/bash
          echo $jjwxp80242 | jq -r .l7 | /bin/bash

